### ISSUE TITLE
[RFC] Adding i18n

### ISSUE THREAD

**Issue by QuintenJustus** [Protoqol/Prequel#33]
# Request For Comments:  Internalization - i18n
I was thinking about all the features that Prequel is still missing and i18n came across my mind, but I'm not really sure if this is worth looking into. That's why I opened this RFC.

## See points below for my thoughts about this.

- Would this be helpful to people?
- Is this worth investing time into?
- Front-end or back-end implementation?
- Are there people willing to translate this?

##### For those unaware of what i18n is, it's basically translating Prequel to other languages.

**Comment by cjfloss** [comment]
> Would this be helpful to people?
It is pretty helpful for people that don't fully understand english.

> Are there people willing to translate this?
I'm willing to translate to Brazilian Portuguese.

**Comment by M4ST3RX** [comment]
Agree with @cjfloss, i can help translate to Hungarian.

**Comment by QuintenJustus** [comment]
Tagging all current contributors for feedback @James-N-M @xuanquynh @mchlbatista @ajthinking @aaronsaray @djaxho

**Comment by aaronsaray** [comment]
I'm a native-english speaker only, so I can't help with translations. That being said, the sooner you implement i18n the better.  This sets up a nice framework for people to contribute. However, keep in mind that the sooner you add more language support, the longer it may take to merge in new features (or enable them) as they'll need translation.  That being said, I'm all for it :)

**Comment by xuanquynh** [comment]
1. Would this be helpful to people?
- Yes, It would be absolutely helpful.
2. Is this worth investing time into?
- We just use English and create the file with full necessary keys. The others will translate into their languages.
3. Front-end or back-end implementation?
- one vote for back-end implementation because this isn't a SPA. Using Laravel vendor locale files is more suitable.
4. Are there people willing to translate this?
- I think there are a lot of people can help. As the answer of the second question, we just use English template. The community will support to translate into their expected languages if they really need.

For example, PHPMyAdmin supports multiple languages, I always use English but my friends love Vietnamese because of our national language. i18n is always necessary for modern software I think.

**Comment by QuintenJustus** [comment]
Well that settles it then. Because i18n probably will not be a breaking change per se and I want to get out a stable release asap this will probably be added shortly after next release. Closing now, thank you all for the feedback, I will keep you updated! 😁👌

**Comment by djaxho** [comment]
Wasn't able to chime in in time, but agreed, just adding the english keys and letting anyone add translation keys is a solid plan :)
